cloud:
  aws:
    credentials:
      access-key: access-key
      secret-key: secret-key
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: files-explorer


server:
  port: 9090

