cloud:
  aws:
    credentials:
      access-key: AKIATS4DL3ZASH264P4N
      secret-key: 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
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: files-explorer


server:
  port: 9090

